[package]
name = "vary"
version = "0.3.0"
authors = ["Dicov (SrDicov) <https://github.com/SrDicov>"]
edition = "2021"

description = "Void User Repository (VUR) helper and build automator for Void Linux"
homepage = "https://github.com/SrDicov/Vary"
repository = "https://github.com/SrDicov/Vary"
license = "GPL-3.0"
keywords = ["void-linux", "xbps", "vur", "packaging", "helper"]
include = [
    "src/**/*",
    "LICENSE",
    "README.md",
    "README.es.md",
    "docs/**/*",
    "etc/**/*",
    "scripts/**/*",
    "template",
]
rust-version = "1.88"

[dependencies]
ansiterm = "0.12.2"
anyhow = { version = "1.0.100", features = ["backtrace"] }
base64 = "0.22"
diffy = "0.4"
dirs = "6.0.0"
indicatif = "0.17"
md-5 = "0.10"
petgraph = "0.6"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10"
tempfile = "3.24.0"
toml = { version = "0.9.10", features = ["preserve_order"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[profile.release]
codegen-units = 1
lto = true

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = { version = "0.1", default-features = false }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["user", "signal", "process", "fs"] }
