pub fn help() {
    println!("Usage:");
    println!("    vary");
    println!("    vary <operation> [...]");
    println!("    vary <package(s)>");
    println!();
    println!("Operations:");
    println!("    vary {{-h --help}}");
    println!("    vary {{-V --version}}");
    println!("    vary {{-S --sync}}        [options] [package(s)]");
    println!("    vary {{-R --remove}}      [options] <package(s)>");
    println!("    vary --repo <cmd>       Manage VUR repositories");
    println!();
    println!("Sync options:");
    println!("    -s --search             Search for packages");
    println!("    -i --info               Show package information");
    println!("    -y --refresh            Refresh VUR git repositories");
    println!("    -u --sysupgrade         Upgrade all packages");
    println!("    -w --downloadonly       Download sources only");
    println!();
    println!("General options:");
    println!("    --noconfirm             Do not ask for confirmation");
    println!("    --yes                   Alias of --noconfirm (-y is refresh, not yes)");
    println!("    --confirm               Ask for confirmation (default)");
    println!("    --color <when>          Color output: always|never|auto");
    println!("    -v --verbose            Increase verbosity (-vv for debug)");
    println!("    -q --quiet              Quiet output");
    println!("    --arch <arch>           Override architecture");
    println!();
    println!("Vary options:");
    println!("    --force-build           Force build from source even if binary exists");
    println!("    --prefer-binary         Prefer binary repos when available (default)");
    println!("    --no-prefer-binary      Always build from source");
    println!("    --sudo <bin>            privilege escalation tool: sudo, doas or run0 (default: auto-detected; unused as root)");
    println!("    --sudoflags <flags>     replace vary.conf flags for the elevation tool");
    println!("    --git <bin>             git binary to use");
    println!("    --curl <bin>            curl binary for remote indexes (default: curl)");
    println!();
    println!("Repo management:");
    println!("    vary --repo add <url> [name] [--branch <rama>] [--index-url <url>]  Add a VUR repository");
    println!("    vary --repo list                  List configured VURs");
    println!("    vary --repo remove <name> [-p]    Remove a VUR (-p also purges the clone)");
    println!("    vary --repo rekey <name>          Re-register binary repo key");
    println!();
    println!("If no arguments are provided 'vary -Syu' will be performed");
    println!();
    println!("Examples:");
    println!("    vary -S foo             Install package foo (resolve+build+install)");
    println!("    vary -Ss bar            Search for bar in official repos and VURs");
    println!("    vary -Syu               Full system upgrade (official + VURs)");
    println!("    vary -R foo             Remove package foo");
}
